# GET root URL
GET http://assignment1-rest-api-extension-hze3daf9etd6cucs.canadacentral-01.azurewebsites.net:8000/
Accept: text/plain

###

# GET health check
GET http://assignment1-rest-api-extension-hze3daf9etd6cucs.canadacentral-01.azurewebsites.net:8000/health
Accept: application/json

###

# GET all users
GET http://assignment1-rest-api-extension-hze3daf9etd6cucs.canadacentral-01.azurewebsites.net:8000/users
Accept: application/json

###

# GET a specific user by ID
GET http://assignment1-rest-api-extension-hze3daf9etd6cucs.canadacentral-01.azurewebsites.net:8000/users/1
Accept: application/json

###

# POST create a new user
POST http://assignment1-rest-api-extension-hze3daf9etd6cucs.canadacentral-01.azurewebsites.net:8000/users
Content-Type: application/json

{
  "name": "Charlie",
  "age": 22
}

###

# PUT update a user by ID
PUT http://assignment1-rest-api-extension-hze3daf9etd6cucs.canadacentral-01.azurewebsites.net:8000/users/1
Content-Type: application/json

{
  "name": "Alice Updated",
  "age": 26
}

###

# DELETE a user by ID
DELETE http://assignment1-rest-api-extension-hze3daf9etd6cucs.canadacentral-01.azurewebsites.net:8000/users/1


